# Generated by Django 5.2.12 on 2026-04-17 19:37

from django.contrib.postgres.operations import (
    CreateExtension,
    TrigramExtension,
    UnaccentExtension,
)
from django.db import migrations


class Migration(migrations.Migration):
    """Initial migration file to create PostgreSQL extensions."""

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        TrigramExtension(),
        UnaccentExtension(),
        CreateExtension("fuzzystrmatch"),
    ]
