# Generated by Django 5.2.13 on 2026-06-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_user_managers_remove_user_metadata_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                default="",
                max_length=254,
                verbose_name="identity email address",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="full name"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("en-us", "English"),
                    ("fr-fr", "Français"),
                    ("de-de", "Deutsch"),
                    ("nl-nl", "Nederlands"),
                ],
                default="",
                help_text="The language in which the user wants to see the interface.",
                max_length=10,
                verbose_name="language",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="short_name",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="short name"
            ),
            preserve_default=False,
        ),
    ]
