name: Update crowdin sources

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  upload:
    permissions:
      contents: read
    uses: suitenumerique/ci/.github/workflows/_crowdin-upload.yml@ca6401ac83e981e5b0a94f06f68baaa6e6d0a436 # v0.0.1
    secrets:
      CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
      CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
