name: Docker images
run-name: Docker images

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  pull_request:
    branches:
      - "main"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build-and-push:
    name: ${{ matrix.service }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - service: backend
            image_name: lasuite/accounts-backend
            context: .
            file: ./Dockerfile
            target: backend-production
          - service: frontend
            image_name: lasuite/accounts-frontend
            context: .
            file: ./src/frontend/Dockerfile
            target: frontend-production
    uses: suitenumerique/ci/.github/workflows/_docker-publish.yml@ca6401ac83e981e5b0a94f06f68baaa6e6d0a436 # v0.0.1
    with:
      image_name: ${{ matrix.image_name }}
      context: ${{ matrix.context }}
      file: ${{ matrix.file }}
      target: ${{ matrix.target }}
      docker_user: "1001:127"
      should_push: ${{ github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'preview') }}
    secrets:
      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

  notify-argocd:
    permissions:
      contents: read
    needs:
      - build-and-push
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'preview')
    steps:
      - uses: suitenumerique/ci/actions/argocd-webhook-notification@ca6401ac83e981e5b0a94f06f68baaa6e6d0a436 # v0.0.1
        with:
          deployment_repo_path: "${{ secrets.DEPLOYMENT_REPO_URL }}"
          argocd_webhook_secret: "${{ secrets.ARGOCD_PREPROD_WEBHOOK_SECRET }}"
          argocd_url: "${{ vars.ARGOCD_PREPROD_WEBHOOK_URL }}"
