name: Helmfile lint
run-name: Helmfile lint

on:
  push:
  pull_request:
    branches:
      - 'main'
    paths:
      - "src/helm/**"
      - ".github/workflows/helmfile-linter.yaml"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  helmfile-lint:
    permissions:
      contents: read
    uses: suitenumerique/ci/.github/workflows/_helmfile-lint.yml@ca6401ac83e981e5b0a94f06f68baaa6e6d0a436 # v0.0.1
    with:
      helmfile_version: v0.171.0
