name: Project quality Workflow
on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  lint-git:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: show
        run: git log origin/${{ github.event.pull_request.base.ref }}..HEAD
      - name: Enforce absence of print statements in code
        if: always()
        run: |
          ! git diff origin/${{ github.event.pull_request.base.ref }}..HEAD -- src/backend ':(exclude)**/git.yml' | grep "print("
      - name: Check absence of fixup or squash commits
        if: always()
        run: |
          ! git log --format=%s origin/${{ github.event.pull_request.base.ref }}..HEAD | grep -E '^(fixup!|squash!)'
      - name: Lint commit messages added to main
        if: always()
        run: |
          pip install --user requests gitlint
          ~/.local/bin/gitlint --commits origin/${{ github.event.pull_request.base.ref }}..HEAD

  lint-spell-mistakes:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install codespell
        run: pip install --user codespell
      - name: Check for typos
        run: |
          codespell \
            --check-filenames \
            --ignore-words-list "Dokument,afterAll,excpt,statics" \
            --skip "./git/" \
            --skip "**/*.pdf" \
            --skip "**/*.po" \
            --skip "**/*.pot" \
            --skip "**/*.json" \
            --skip "**/uv.lock" \
            --skip "**/yarn.lock"

  check-shell-scripts:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Check shell scripts
        run: find . -type f -name '*.sh' -exec shellcheck --external-sources {} +
