name: Release Chart
run-name: Release Chart

on:
  push:
    branches:
      - main
    paths:
      - src/helm/accounts/**
      - ".github/workflows/release-helm-chart.yaml"

permissions:
  contents: read

jobs:
  release:
    permissions:
      contents: write
    uses: suitenumerique/ci/.github/workflows/_release-helm-chart.yml@ca6401ac83e981e5b0a94f06f68baaa6e6d0a436 # v0.0.1
    with:
      linting: false
